var useState = React.useState;
var useCallback = React.useCallback;
var useEffect = React.useEffect;

// ============ TICKET DATA (reloaded May 13, 2026) ============
var TICKETS_ALBERT = [
  { id:"WOCOO-21505", summary:"CC authorized transaction", type:"Credit Card: Transactions", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-14", description:"Premium client authorized $300 Enterprise car rental transaction pending since Nov 21 2025. Investigate. identity-WF9JR3gmtSIS4M8u9nrfQN6gbSP" },
  { id:"WOCOO-21502", summary:"Prepaid Card Declined Transaction", type:"Prepaid Card: Transactions", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-13", description:"Core client Amazon declined for NSF despite sufficient funds in chequing. Was resolved May 1st previously. identity-ZDjBJyw9Rf9iNk9TrdkwKSatXXH" },
  { id:"WOCOO-21499", summary:"Credit Card Suspected Fraud Block", type:"Credit Card: Transactions", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-13", description:"Core client CC blocked due to incorrect CVV attempts, unblocked but now Walmart triggering fraud alert. identity-wdachlNVoH6zF3t7FYlWuF02YTT" },
  { id:"WOCOO-21494", summary:"Missing refund $122.50 (merchant states funds deposited to WS)", type:"Credit Card: Transactions", status:"Triage [New Tickets]", priority:"Medium", labels:"jira_escalated", created:"2026-05-13", description:"Core client missing $122.50 refund. Merchant ARN: 12305456107000000183049. Not in activity/transfers/KOHO/i2c. identity-AKDMbswswsWJXoP8TnV5l7L1cx6" },
  { id:"WOCOO-21493", summary:"Unable to add CC to digital wallet", type:"Credit Card: Digital Wallet", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-13", description:"Core client unable to add CC to digital wallet. identity-R65b3NRqknzyUNXBeKOtxEzcn1O" },
  { id:"WOCOO-21490", summary:"VI+ card instead of VIP Card", type:"Credit Card: Onboarding", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-13", description:"Premium client input wrong income info; qualifies for VIP. Can we upgrade or wait for VI+ to be received? identity-rrxGor9tsGR90faFZzOYXCCdpmu" },
  { id:"WOCOO-21482", summary:"3DS on CC transactions not received by SMS", type:"Cash: Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-13", description:"Core client buying airline tickets not receiving SMS 3DS code; email works. Phone matches on file. identity-Gr4MT3mh4MCSR2ICJsLhLcI4jlj" },
  { id:"WOCOO-21480", summary:"Eligibility Confirmation Request", type:"Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-13", description:"Confirm activation date and good standing. Last 4: 7936. Kwok-King Ving. DOL: May 6, 2026" },
  { id:"WOCOO-21477", summary:"address", type:"Credit Card: Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-13", description:"Core client virtual CC issuance failing — address too long. Has tried shortening with no luck. identity-0HAWXkn5qFCeVqke5J81e3r9w0J" },
  { id:"WOCOO-21468", summary:"Custom statement for specific CC transaction", type:"Credit Card: Statements", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-13", description:"Premium client needs custom statement for $2515.84 rental car damage transaction May 6. CC opened 15th, statement June 5 too late for insurance. identity-vK15qp8TRtjTRD7O5m6coiHm8zY" },
  { id:"WOCOO-21467", summary:"Unable to add overdraft protection to account", type:"Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-13", description:"Premium client cannot see overdraft protection option on chequing. Mirrored profile - option not visible. identity-eybSrih5E6No2XeVdXFv6XsJmdd" },
  { id:"WOCOO-21456", summary:"Reversing a CC payment", type:"Credit Card: Overpayment", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-13", description:"Core client wants $3000 CC payment reversed. Already made downpayment to Nissan, wants cash in chequing. identity-LyNMPixudvjirJiwoJjFeKKDWmE" },
  { id:"WOCOO-21452", summary:"Eligibility Confirmation Request", type:"Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-12", description:"Confirm activation date and good standing. Last 4: 8678. Ishapal Arora. DOL: April 20, 2026" },
  { id:"WOCOO-21422", summary:"Remaining balance after account closure", type:"Prepaid Card: Transactions", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-12", description:"Core client moved to US, $403.48 remaining in WK6VCT035CAD. No Canadian bank account, has US Lead bank account. identity-57oxroBS0Xp7hUkeFRkcNFWYvz7" },
  { id:"WOCOO-21418", summary:"Mastercard Decline", type:"Prepaid Card: Transactions", status:"Triage [New Tickets]", priority:"Medium", labels:"jira_escalated", created:"2026-05-12", description:"Core client virtual PPMC decline code 46. Test transactions went through with agent. Investigate decline reason 'unknown'. identity-C5fd3Fy0PRegfrVKKWRriYZ1Kou" },
  { id:"WOCOO-21417", summary:"Unable to add CC to Google Wallet - Contact card issuer error", type:"Credit Card: Digital Wallet", status:"Triage [New Tickets]", priority:"Medium", labels:"jira_escalated", created:"2026-05-12", description:"Generation client reset Android, cannot add Visa Infinite to Google Wallet. Card active, not locked. identity-has3u2wQPufa2L24KkdPIO8_WBY" },
  { id:"WOCOO-21416", summary:"CC onboarding issue", type:"Credit Card: Onboarding", status:"Triage [New Tickets]", priority:"Medium", labels:"jira_escalated", created:"2026-05-12", description:"Core client error completing CC application. Worried about expiry. identity-498nGSziIT5fBirQr6R6LsITqMP" },
  { id:"WOCOO-21415", summary:"Eligibility Confirmation Request", type:"Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-12", description:"Confirm activation date and good standing. Last 4: 1853. ROSANNA ZHANG. DOL: February 1, 2026" },
  { id:"WOCOO-21414", summary:"Eligibility Confirmation Request", type:"Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-12", description:"Confirm activation date and good standing. Last 4: 4099. Harry Yunche Wu. DOL: April 30, 2026" },
  { id:"WOCOO-21405", summary:"CSV of transactions since activation", type:"Credit Card: Statements", status:"Triage [New Tickets]", priority:"High", labels:"jira_escalated", created:"2026-05-11", description:"Generation client needs CSV of purchases to calculate 5% cashback threshold met. identity-GatlmsUeg5uHOcrnChxqtPgvFUs" },
  { id:"WOCOO-21403", summary:"Physical Card Activation", type:"Credit Card: Physical Card", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-11", description:"Premium client unable to activate physical card using QR code. No option in WS app. identity-bpDG27DVIwH5MTPkpkP4Izi6enc" },
  { id:"WOCOO-21393", summary:"Credit Card Limit Increase Request", type:"Credit Card: Digital Wallet", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-11", description:"Generation client wants CC limit raised from $10k to $15k. identity-yauVABU20vhU64h22hIsS4Gb2HU" },
  { id:"WOCOO-21391", summary:"Increase Inquiry", type:"Credit Card: Limit Increase", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-11", description:"Premium client wants CC limit increased to maximum. identity-n6AQKBKT1OgntIPLekEps4EV3J7" },
  { id:"WOCOO-21389", summary:"Client card declining - Insufficient funds 51 but has enough", type:"Prepaid Card: Transactions", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-11", description:"Core client PPMC declining code 51. Koho shows $0 at txn time but Atlas shows enough. identity-ogljdxEivlrjWSAA2W9vCNdBgrG" },
  { id:"WOCOO-21387", summary:"Pending Credit Card Transaction", type:"Credit Card: Transactions", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-11", description:"Core client CC trxn pending since April 23rd. Merchant says cancelled April 24th but not reflected. identity-VAH2j9bPJzrqUfXEH1t5uTBVQ8" },
  { id:"WOCOO-21386", summary:"Credit card fee-waiver / Quebec annual fee issue", type:"Credit Card: Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-11", description:"Core client expecting $20 fee waiver, now premium, did not get rebate. Apply missing refund. identity-TfcQ8PGY9keFgTnHCf0FaGl7mP1" },
  { id:"WOCOO-21385", summary:"Adding Mastercard to Applepay", type:"Prepaid Card: Digital Wallet", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-11", description:"Core client unable to add Mastercard to Apple Pay, getting error. identity-RRCo0T0GxUFNXsJPFFer4yavPDW" },
  { id:"WOCOO-21362", summary:"CC Statement Address Discrepancy Investigation", type:"Credit Card: Statements", status:"Triage [New Tickets]", priority:"Highest", labels:"jira_escalated", created:"2026-05-09", description:"Generation client March statement displayed incorrect address. April statement shows mailing instead of residential. identity-61DdQ9D1c5J5p46I5OL4FIAsXgC" },
  { id:"WOCOO-21357", summary:"Reverse fee", type:"Credit Card: Other", status:"Back Office", priority:"Medium", labels:"jira_escalated", created:"2026-05-09", description:"Core client wants $20 monthly fee reversed, had card 2 days. identity-KRr3dLjnEN1gpYsu4hUl4Fl3Sog" },
  { id:"WOCOO-21349", summary:"Declined Transactions with Amazon despite Sufficient Funds", type:"Prepaid Card: Transactions", status:"Triage [New Tickets]", priority:"Medium", labels:"jira_escalated", created:"2026-05-08", description:"Core client card declining Amazon code 51. 3DS failure suspected. identity-FtFa5zUmh8Ihjd1ecOK00GVAzUa" },
  { id:"WOCOO-21272", summary:"Boosted interest rate", type:"Cash: Interest", status:"Triage [New Tickets]", priority:"Medium", labels:"jira_escalated", created:"2026-05-07", description:"Core client has 1.25% instead of 1.75% boosted rate. DD $2460.92 in April. identity-VgB9H9KjtTv0hmuytzyXITyGAlQ" },
  { id:"WOCOO-21430", summary:"PPMC: unable to unlock/activate/reissue", type:"Prepaid Card-related Issues", status:"Triage [New Tickets]", priority:"Medium", labels:"jira_escalated", created:"2026-05-07", description:"Core client cannot unlock/activate PPMC ending 5413. KOHO shows locked. Activation flow errors. identity-M3agdYxppOL8ihzqYTVe3sjVFaE" },
  { id:"WOCOO-21240", summary:"Amex CC Payment", type:"Cash: Bill Payment", status:"Back Office", priority:"Medium", labels:"jira_escalated", created:"2026-05-06", description:"Premium client unable to complete AmEx payment. AmEx says cancelled on our end. identity-NHKS2QLNrSjautDY9vFOjvHaZqC" },
  { id:"WOCOO-21206", summary:"Multiple Failed Trxns in Prepaid MC (Virtual)", type:"Prepaid Card: Transactions", status:"Back Office", priority:"Medium", labels:"jira_escalated", created:"2026-05-05", description:"Core client multiple failed virtual PPMC trxns. PayPal, Apple, Temu. All code 63. identity-mLtmonvAaGi7yzULoQOI5g4wsvz" },
  { id:"WOCOO-21181", summary:"Client card is active but still declining", type:"Credit Card: Transactions", status:"Back Office", priority:"Medium", labels:"jira_escalated", created:"2026-05-05", description:"Core client declines code 59, E7, 54. Card active but reacting as if locked. identity-1Uw9jp1lfDRSreOEJdfTyAZAsHB" },
  { id:"WOCOO-21176", summary:"Interest Charge", type:"Credit Card: Other", status:"Triage [New Tickets]", priority:"Medium", labels:"jira_escalated", created:"2026-05-05", description:"Core client interest charge from accidental cash withdrawal from CC. Confirm and reverse. identity-9E8BEkvJZ5SdSqXR1dgcAnAezVt" },
  { id:"WOCOO-21098", summary:"CC Cashback not reflected from a purchase", type:"Credit Card Issues", status:"Back Office", priority:"Medium", labels:"jira_escalated", created:"2026-05-01", description:"Core client cashback not reflected from SP Barbecues Galore $65.10. Settled. identity-3ggst8v3wzy1QrSTS_neo1Om144" },
  { id:"WOCOO-21042", summary:"BIXI - card-expiry-mismatch declines", type:"Credit Card: Transactions", status:"Pending CS", priority:"High", labels:"jira_escalated", created:"2026-04-29", description:"Premium client BIXI Montreal declined card-expiry-mismatch despite correct expiry. identity-cMZVvNH1rde0Aqbw76jrP1g0tw" },
  { id:"WOCOO-20936", summary:"Unauthorized repeat transactions", type:"Prepaid Card: Transactions", status:"Back Office", priority:"Medium", labels:"jira_escalated", created:"2026-04-27", description:"Core client persistent unauthorized charges from 9542-1061 QUEBE. Cards reissued, charges continue. identity-OHOlXLvoR4vVczmY16uMisyQbAS" },
  { id:"WOCOO-20926", summary:"Charged interest despite auto-pay", type:"Interest-Related Issues", status:"Pending CS", priority:"Highest", labels:"jira_escalated", created:"2026-04-26", description:"Generation client auto-pay statement balance, charged $0.10 in March and April. identity-LVJDT4mUULUI0WFTqZnwjTL9Ro" },
  { id:"WOCOO-20923", summary:"CC - Autopay Issue", type:"Credit Card: Other", status:"Back Office", priority:"Medium", labels:"jira_escalated", created:"2026-04-26", description:"Generation client autopay shows completed amount: 0 despite having funds. identity-mqG017HIk1B0KdzCewG0pWKbDdg" },
  { id:"WOCOO-20823", summary:"Declining Prepaid Mastercard Transactions", type:"Prepaid Card: Transactions", status:"Pending CS", priority:"Medium", labels:"jira_escalated", created:"2026-04-23", description:"Core client PPMC declined for Air Canada. ID verify with passcode but no prompt to enter. identity-M30NW8VNAXILJcomjLjBmJ57Qk0" },
];

var TICKETS_ESTHER = [
  { id:"WOCOO-21472", summary:"Wires to post May 13 USD and CAD", type:"Wires Posting", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-13", description:"Multiple USD and CAD wires to post May 12-13. JPMorgan Chase, Wells Fargo, RBC, HSBC, CIBC. Large batch including $89,940 RBC and $50,755 Wells Fargo." },
  { id:"WOCOO-21470", summary:"Eligibility Confirmation Request", type:"Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-13", description:"Confirm activation date and good standing. Last 4: 6656. Sean Marsden. DOL: April 1, 2026" },
  { id:"WOCOO-21464", summary:"Eligibility Confirmation Request", type:"Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-13", description:"Confirm activation date and good standing. Last 4: 0221. Sarah Clinton-Baker. DOL: April 11, 2026" },
  { id:"WOCOO-21457", summary:"Eligibility Confirmation Request", type:"Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-13", description:"Confirm activation date and good standing. Last 4: 0806. DOL: March 9, 2026" },
  { id:"WOCOO-21454", summary:"Eligibility Confirmation Request", type:"Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-13", description:"Confirm activation date and good standing. Marchin, Denis. DOL: April 19, 2026" },
  { id:"WOCOO-21424", summary:"PPMC - We're preparing your card", type:"Prepaid Card: Onboarding", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-12", description:"Core client no virtual PPMC after 3 months. No KOHO account under profile email. identity-CpnPKxpITcqwInP6zG4dsgIbVau" },
  { id:"WOCOO-21421", summary:"Credit card refund from FIFA", type:"Credit Card: Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-12", description:"Premium client expecting refund from FIFA over 5-7 business days. FIFA confirms funds returned to card. identity-euBPgPoVr0tawsfOVjh4L5T1tfm" },
  { id:"WOCOO-21420", summary:"VISA Airport Companion Program Enrolment Issues", type:"Credit Card: Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-12", description:"Generation client card verification keeps failing for Visa Airport Companion. Card is active. identity-2Odq0FI8QoNOR2ZR4TiDIZjX72m" },
  { id:"WOCOO-21419", summary:"Hard Check Removal", type:"Credit Card: Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-12", description:"Core client opened CC May 10, closing due to fees and DD not meeting $4k threshold. Remove TU hard check. identity-Ozw3ioqXUnMC1PAnaLJ5e9UpA7z" },
  { id:"WOCOO-21404", summary:"Corp Account statement discrepancy", type:"Cash: Other", status:"Triage [New Tickets]", priority:"High", labels:"jira_escalated", created:"2026-05-11", description:"Generation client two corp chequing accounts both have statement discrepancy (Cash and Brokerage). identity-b1sjXyMUva2AFWXcW4XyMj0hEKE" },
  { id:"WOCOO-21401", summary:"CC interest reversal request", type:"Credit Card: Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-11", description:"Core client paid 4 hours late due to being overseas. Reverse $80.31 interest as one-time gesture. identity-6p5dROkVaDcftv244MLn6DP4Wic" },
  { id:"WOCOO-21394", summary:"Client unable to use CC, decline code 61 and 57", type:"Prepaid Card: Transactions", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-11", description:"Core client Quasi Cash/Cash Advance. CA limits Allocated $2040, Available $1043.87. Client within range. identity-VKaunEjXJbVtEXVUB0czcwNRmw4" },
  { id:"WOCOO-21392", summary:"Google Wallet", type:"Credit Card: Digital Wallet", status:"Triage [New Tickets]", priority:"High", labels:"jira_escalated", created:"2026-05-11", description:"Premium client Google says token issue, need to redistribute. identity-eEs58G9Pi3QxfB46QrrB47URQXj" },
  { id:"WOCOO-21390", summary:"Visa Companion Airport not recognizing card", type:"Credit Card: Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-11", description:"Core client cannot sign up for Visa Companion Airport. Card not recognized. identity-tSBVJkITVQ8TChhMHTllBH9owOW" },
  { id:"WOCOO-21383", summary:"AppCharge $19.20 went through but service not received", type:"Prepaid Card: Transactions", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-11", description:"Core client AppCharge $19.20 April 30 went through on Atlas but merchant says cancelled. identity-x5UQ9gx0fj5EkjM1byfjViXScvU" },
  { id:"WOCOO-21381", summary:"Client unable to activate credit card received in mail", type:"Credit Card: Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-11", description:"Core client receiving 'card not found' error when activating CC. identity-2m2sXG7b9AQZqfRsyOsJMtb3h_g" },
  { id:"WOCOO-21380", summary:"TikTok Failed Payments", type:"Credit Card: Transactions", status:"Triage [New Tickets]", priority:"Medium", labels:"jira_escalated", created:"2026-05-11", description:"Core client all declined transactions code 63. All TikTok payments April 29-May 9 failed. WK7LNXW30CAD identity-IoeOaYz7Jd357Y6Ue3gIZyxRT5n" },
  { id:"WOCOO-21379", summary:"Overpayment/Double Charge", type:"Credit Card: Transactions", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-11", description:"Premium client Feb 2025 statement balance $216.59 but charged $283.26. Also charged twice. identity-eh4WGS1AaVaQP6aVJ2JHhA3cPex" },
  { id:"WOCOO-21377", summary:"Monthly CC fee waiver request", type:"Credit Card: Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-11", description:"Core client wants monthly CC fee waived. $100k+ in corporate investing account. identity-GCqPrDhVs2Ij2a0qorUcXs8jbQa" },
  { id:"WOCOO-21375", summary:"Credit Card Overpayment: Duplicate Payment", type:"Credit Card: Overpayment", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-11", description:"Core client duplicate payment, reverse one of duplicate payments of $3763.81. identity-33nf8gcJImhvnl_H9EDSz2_I7Y" },
  { id:"WOCOO-21374", summary:"Refund transfer request", type:"Credit Card: Overpayment", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-11", description:"Premium client transfer $5000 from Visa CC to chequing WK1PKP230CAD. identity-TtpQKpfzQNVLz5Vo4sCMF6JTX24" },
  { id:"WOCOO-21373", summary:"Client unable to add CC to Digital Wallet", type:"Credit Card: Digital Wallet", status:"Triage [New Tickets]", priority:"Medium", labels:"jira_escalated", created:"2026-05-11", description:"Premium client unable to add CC to digital wallet after troubleshooting steps. identity-m9kzqISfDxS2730GCJt1qCaKWbY" },
  { id:"WOCOO-21371", summary:"International CC transaction declined invalid CVV/expiry", type:"Credit Card: Transactions", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-11", description:"Core client $60 EUR Athens Greece declined code E7. Correct CVV/expiry. Card active. identity-S3lui8z2AhMg00XYsBja9BZysLE" },
  { id:"WOCOO-21361", summary:"Chequing account balance check", type:"Other", status:"Back Office", priority:"Medium", labels:"", created:"2026-05-09", description:"Client chequing balance after $150 e-transfer May 5 was $204. May 6 showed $176, no transactions. identity-pdZVDSoEUR86ZCrUWyQlwHCiuJF" },
  { id:"WOCOO-21359", summary:"Premium Client Charged CC Fee", type:"Credit Card: Other", status:"Pending CS", priority:"Medium", labels:"jira_escalated", created:"2026-05-09", description:"Premium client charged CC fee, mistake? Reimburse. identity-WQL3pSat9eEQeQCyVlsih4QS29M" },
  { id:"WOCOO-21351", summary:"Chequing account balance discrepancy", type:"Cash: Other", status:"Back Office", priority:"Medium", labels:"", created:"2026-05-08", description:"Core client April statement shows $445.10 after $400 deposit, but Preset shows $400.08. WK4XW8X31CAD identity-L8ateNDp9EZgf7TdMDhVeSqK7FH" },
  { id:"WOCOO-21345", summary:"Not Able to Activate Credit Card", type:"Credit Card: Physical Card", status:"Pending CS", priority:"Medium", labels:"", created:"2026-05-08", description:"Premium client CC activation error with QR code. Activate option greyed out. identity-Ut9ci5fksqGTpZgui7M8Mp8JDTZ" },
  { id:"WOCOO-21343", summary:"Missing Funds", type:"Cash: E-transfers", status:"Back Office", priority:"Medium", labels:"", created:"2026-05-08", description:"Core client believes missing funds in chequing. Should have $728.57. identity-aGhhJ2rnXvWohc2dkiC4SvtVccQ" },
  { id:"WOCOO-21342", summary:"TM decline - declined-chip-transaction-not-allowed Akal Optical", type:"Credit Card: Transactions", status:"Pending External", priority:"Medium", labels:"", created:"2026-05-08", description:"Premium client CC tap not working. Akal Optical declined-chip-transaction-not-allowed (TM). identity-ctJ2YEwwSJKMOJpoks8lqe4HcXK" },
  { id:"WOCOO-21341", summary:"Credit Card overpayment", type:"Credit Card: Overpayment", status:"Back Office", priority:"Medium", labels:"", created:"2026-05-08", description:"Premium client overpayment $1,539.66 to move back to chequing account. identity-k75D0My2UVARxrQqRGKRKaPMvb0" },
  { id:"WOCOO-21340", summary:"Missing merchant refund - OLA", type:"Prepaid Card: Transactions", status:"Pending CS", priority:"Medium", labels:"", created:"2026-05-08", description:"Core client missing refund from OLA merchant. $204.65. Receipt attached. identity-ehqh9YZ0ze7oJoj6WkdUVgYiiyL" },
  { id:"WOCOO-21336", summary:"Code 63 declined - Negative balance", type:"Prepaid Card: Transactions", status:"Pending External", priority:"Medium", labels:"", created:"2026-05-08", description:"Core client multiple declines code 63. Cash Time Travel shows -$17k vs Atlas $3100. identity-EezOUfCyiCaMEpZoMk4sWwbYYML" },
  { id:"WOCOO-21334", summary:"Overpayment Reversal Request - URGENT", type:"Credit Card: Overpayment", status:"Back Office", priority:"Highest", labels:"", created:"2026-05-08", description:"Core client overpaid CC. Current balance -$3,090.01, urgently needs for rent. identity-EP7WTOnus7Qhjk2zLLnJPHeutSm" },
  { id:"WOCOO-21308", summary:"Manual CC Wait List // Credit Balance Transfer", type:"Credit Card: Other", status:"Back Office", priority:"Medium", labels:"jira_escalated", created:"2026-05-07", description:"Core client wants Visa Infinite Privilege but previous card has balance owed. identity-eNw6nrD48r3RzZJbN2ZpUPWEDvT" },
  { id:"WOCOO-21291", summary:"Refund Discrepancy", type:"Credit Card: Statements", status:"Back Office", priority:"High", labels:"jira_escalated", created:"2026-05-07", description:"Premium client $133.76 refund showing as balance owed in statement. identity-kMOwl31_Kmqs5uCwPTRxEBnwrE" },
  { id:"WOCOO-20010", summary:"Credit Card Overpayment", type:"Credit Card: Transactions", status:"Pending Settlement", priority:"Medium", labels:"jira_escalated", created:"2026-03-23", description:"Premium client overpayment to reverse to chequing. Bring CC balance to $0. identity-dnJx7Uq0x4vRBsTzzAhEBvzPvbz" },
];

var TICKETS_LUKE = [
  { id:"WOCOO-21433", summary:"Unable to register for Visa Airport Companion with VIP card", type:"Credit Card: Rewards", status:"Triage [New Tickets]", priority:"Medium", labels:"jira_escalated", created:"2026-05-12", description:"Core client cannot register for Visa Airport Companion with VIP card. Product ID = ws_visa_infinite_privilege but RPIN is Blank. identity-sPkaySnWzgnVTh3kJxCtXbdDCPV" },
  { id:"WOCOO-21230", summary:"Client unable to add virtual card to digital wallet", type:"Prepaid Card: Digital Wallet", status:"Pending External", priority:"Medium", labels:"jira_escalated", created:"2026-05-06", description:"Core client unable to add virtual card to digital wallet. CARD NOT ADDED error. WK60XHF30CAD identity-OnVlLHAHeyJmPZ6la7SFOsi0Krt" },
  { id:"WOCOO-21254", summary:"Missing Balance: Transaction not in Atlas Activities", type:"Prepaid Card-related Issues", status:"Pending CS", priority:"Highest", labels:"jira_escalated", created:"2026-05-05", description:"Client missing $200 e-transfer balance. Transaction 'spend-***' shows but not in activities. identity-3uxNCC2YgLzAngyWMEQeZsnh1Ns" },
  { id:"WOCOO-21186", summary:"Client wrong address on CC statement", type:"Credit Card: Statements", status:"Triage [New Tickets]", priority:"Medium", labels:"jira_escalated", created:"2026-05-05", description:"Premium client moved Feb, updated address on WS but April statement still old address. identity-y9y5mL7gKRLDCSAIzp3Y3ZENM16" },
  { id:"WOCOO-21116", summary:"Google Wallet Troubleshooting", type:"Credit Card: Other", status:"Pending CS", priority:"Medium", labels:"jira_escalated", created:"2026-05-01", description:"Core client unable to add virtual card to Google Wallet. App says contact WS. identity-TqJ1In3jEgqiptUB0jMFf5iorHA" },
  { id:"WOCOO-21148", summary:"3DS challenge failing for BC Ferries and Chexy", type:"Prepaid Card-related Issues", status:"Pending External", priority:"High", labels:"jira_escalated", created:"2026-04-29", description:"Generation client 3DS challenge failing for BC Ferries and Chexy. ACS errors with Support IDs. identity-fNnvHsVOVdDAr8D0fpcqdSIwlq0" },
  { id:"WOCOO-19934", summary:"PAD issues for business chequing", type:"Cash: Bill Payment", status:"Pending External", priority:"Medium", labels:"jira_escalated", created:"2026-03-18", description:"Core client set up PADs with Industrial Alliance and Bennington but companies cannot find account. WK74J1C01CAD identity-y0bGAq4y03fWlE9lGjh3rFDyj4Y" },
  { id:"WOCOO-19795", summary:"Visa - Google Wallet Issues", type:"Credit Card: Digital Wallet", status:"Back Office", priority:"Medium", labels:"jira_escalated", created:"2026-03-12", description:"Premium client got new phone, error when adding Visa to Google Wallet. identity-OSsYRlmGTtcyHjtLclpNCUzY3jM" },
  { id:"WOCOO-19030", summary:"Client's $106.99 ATM withdrawal failed but funds missing", type:"Prepaid Card: Transactions", status:"Back Office", priority:"Medium", labels:"jira_escalated", created:"2026-02-09", description:"Core client ATM withdrawal $106.99 failed but funds are missing. identity-6jlipbPyqylnI80FuDF880s6x9l" },
  { id:"WOCOO-18650", summary:"Google Pay - something went wrong", type:"Credit Card: Digital Wallet", status:"Back Office", priority:"Medium", labels:"jira_escalated", created:"2026-01-26", description:"Premium client unable to add CC to Google Wallet for months. identity-TI3tnANSCKWhRdRVpMOXmAbzBec" },
];

var TICKETS_ISHAN = [
  { id:"WOCOO-21471", summary:"Credit card declined | Suspended (Apple Pay Berlin)", type:"Credit Card: Digital Wallet", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-13", description:"Premium client CC declined Apple Pay in Berlin, notification said account suspended. No current restrictions, completed transactions after. identity-e6WqpfFKmZTQDnnEztJauXBZ8NI" },
  { id:"WOCOO-21469", summary:"Client address is not acceptable for Application", type:"Credit Card: Onboarding", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-13", description:"Core client address not accepted for CC application. Lives on farmland. PO Box 453. identity-s74nC8tPtYr5NnpyCv3rxHuEnEq" },
  { id:"WOCOO-21465", summary:"Two FlightHub refunds creating -$13,626.96 balance", type:"Credit Card: Overpayment", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-13", description:"Generation client two settled FlightHub refunds $6,813.48 each posted to VIP card. Move $13,626.96 to WK6RMW432CAD. identity-tFX_rNikKVggsNxMBXaGyi612zw" },
  { id:"WOCOO-21461", summary:"Credit Card Overpayment $10,893.25", type:"Credit Card: Overpayment", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-13", description:"Premium client received refund and has overpayment of $10,893.25 CAD. Chequing WK17S8131CAD. identity-ecuf4JX3BlZ6kbJO07b15ZXYVzy" },
  { id:"WOCOO-21460", summary:"Metal credit card: QR activation fails, issuance blocked", type:"Credit Card: Physical Card", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-13", description:"Premium client metal CC issuance blocked reason-card-not-received-by-fulfillment-provider. QR activation fails. identity-gb27ieniGF7lntlWqNFm4mrkjrf" },
  { id:"WOCOO-21453", summary:"Transaction Pending Since JAN22 (Lyft)", type:"Credit Card: Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-12", description:"Core client Lyft pending $33.88 since January 22. Lyft confirmed payment not sent. Remove hold. identity-2spW9FgqCJyc0F6YMjtKHHSelEB" },
  { id:"WOCOO-21450", summary:"CC Transaction Inquiry - subscription block", type:"Credit Card: Transactions", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-12", description:"Core client trying to cancel '222' merchant subscription. Can we block merchant or remove tokens? identity-tHS2bTPwJqd8SJnDcbOLuGgTSvR" },
  { id:"WOCOO-21449", summary:"Declined PP MC code 65 (velocity limit)", type:"Prepaid Card: Transactions", status:"Triage [New Tickets]", priority:"Medium", labels:"jira_escalated", created:"2026-05-12", description:"Core client PPMC declined multiple times May 12 code 65 velocity limit. Confirm daily limit. identity-pjk1bOPAQInHmhn0OPwOtOxmsZy" },
  { id:"WOCOO-21447", summary:"Close cc application", type:"Credit Card: Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-12", description:"Client wants CC application closed, cannot pay fee. identity-TbSwJ2sVOQt2r1NNkrQ2Dsk2vfY" },
  { id:"WOCOO-21446", summary:"Credit Card Fee Reversal (Quebec close)", type:"Credit Card: Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-12", description:"Core client Quebec wants to close credit account but has balance from annual fee. Reverse fee. identity-KIti8GEZbcgZyQfCFErh5E7R28f" },
  { id:"WOCOO-21445", summary:"Card Not working for Certain Transaction types", type:"Credit Card: Transactions", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-12", description:"Generation client CC not completing online/mobile transactions (Mary Browns, Rona, etc). Other CCs work. identity-2Wvldr19ozBeOrZHj0BpParck3B" },
  { id:"WOCOO-21444", summary:"Client unable to complete Credit Card application", type:"Credit Card: Onboarding", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-12", description:"Core client CC application asking to call for additional verification. identity-CJBhS3GG0aIR6yNSwlzfXmw6qOD" },
  { id:"WOCOO-21443", summary:"cc application closure", type:"Credit Card: Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-12", description:"Core client wants to close CC application. identity-gtxIr8JvtDAhSoV5II6ikPclT9L" },
  { id:"WOCOO-21440", summary:"April Statement (closed card still showing balance)", type:"Credit Card: Statements", status:"Triage [New Tickets]", priority:"Medium", labels:"jira_escalated", created:"2026-05-12", description:"Core client CC closed but app shows April statement due $220, fee reversed. Confirm zero balance. identity-DlZQSvUIPp7p3cFj4TNV1wRHAFK" },
  { id:"WOCOO-21436", summary:"Visa airport companion access", type:"Credit Card: Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-12", description:"Core client unable to enroll in Visa Airport Companion despite eligible card. identity-2OyIG1bgOuKaIIqBstpnpPXPus" },
  { id:"WOCOO-21432", summary:"TM technology-mismatch decline (virtual only)", type:"Credit Card: Transactions", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-12", description:"Premium client declined-chip-transaction-not-allowed (TM). No physical card, only virtual. identity-81l5J7hPE5hagyt74LxLylmJ94A" },
  { id:"WOCOO-21431", summary:"Credit card: Overpayment reimbursement $12,000", type:"Credit Card: Overpayment", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-12", description:"Core client accidentally paid CC with entire chequing balance. Return $12,000 to chequing. identity-9bYnEjJ477bBpHyBIb41cf7x91p" },
  { id:"WOCOO-21428", summary:"Remove PAD stop payment block", type:"Cash: DD/PAD", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-12", description:"Premium client PAD to Interactive Brokers $2000 blocked payment_stopped. Remove block. identity-imwkOX1TxRglKPc7eRVxm3zOtG8" },
  { id:"WOCOO-21406", summary:"cc overpayment", type:"Credit Card: Other", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-11", description:"Core client 2 refunds caused additional balance on CC. Reverse additional overpayment to chequing. identity-FzIqQ9YN8Cv064NSTSPQ7enLCX7" },
  { id:"WOCOO-21402", summary:"CC Application Issues", type:"Credit Card: Onboarding", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-11", description:"Core client unable to complete CC application. ID rejected, manually verify with uploaded IDs. identity-0pXjZ8dtt5yNz8NgaDzehzlvF3h" },
  { id:"WOCOO-21398", summary:"Negative Cash Balance - Spending Account", type:"Prepaid Card: Transactions", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-11", description:"Core client has negative balance on spending account. No recent reversed deposits. identity-KCO7XQpSrkzB9HBPnWjlhvbqCzU" },
  { id:"WOCOO-21397", summary:"Refund transfer request from cc to chequing", type:"Credit Card: Overpayment", status:"Triage [New Tickets]", priority:"Medium", labels:"", created:"2026-05-11", description:"Core client $5k transfer from CC to WK2HFWH32CAD. identity-GL5q9yGhuNBgC_cM2UGuIyyFuK0" },
  { id:"WOCOO-21363", summary:"$50 balance discrepancy on Credit Card", type:"Credit Card: Transactions", status:"Pending CS", priority:"Medium", labels:"", created:"2026-05-10", description:"Generation client claims total charges off by $50. Should be $2621.66, system shows $2671.66. identity-Zb7OI20KPk6gO5WDywynCB5N5gV" },
  { id:"WOCOO-21311", summary:"cvv", type:"Credit Card: Other", status:"Back Office", priority:"Medium", labels:"", created:"2026-05-08", description:"Core client activated CC but still different CVV/expiry, name shows previous issued. identity-167mefFwimoJc81XvujFP5lerxi" },
  { id:"WOCOO-21250", summary:"$10K transferred to CC, request reversal $9,500", type:"Credit Card: Overpayment", status:"Back Office", priority:"Medium", labels:"jira_escalated", created:"2026-05-06", description:"Premium client accidentally transferred $10K to WS CC. Hold removed by merchant. Wants $9,500 back. identity-eKfXCoQHtu2wZvsFnxkAfmHUCqN" },
  { id:"WOCOO-21247", summary:"Custom bank letter for payroll", type:"Cash: Other", status:"Back Office", priority:"Medium", labels:"jira_escalated", created:"2026-05-06", description:"Generation client needs custom bank letter for Payment Evolution payroll. PFO cannot sign. Create letter first. identity-2WFu8wLnkxEiMyn08ZEW3KxjqWc" },
  { id:"WOCOO-21242", summary:"PPMC - Apple Wallet provisioning failure - code 63", type:"Prepaid Card: Digital Wallet", status:"Pending External", priority:"Medium", labels:"", created:"2026-05-06", description:"Core client cannot add PPMC to Apple Wallet on new iPhone. Contact card issuer error. Codes 63 and 73. identity-fzhOmoBJtbyn3uHqOLijYguMzmD" },
  { id:"WOCOO-21233", summary:"Auto-Payment Overpayment", type:"Credit Card: Overpayment", status:"Pending CS", priority:"Medium", labels:"jira_escalated", created:"2026-05-06", description:"Premium client auto-payment paid full balance ($7,215.57) instead of statement ($3,409.24). Refund $3,806.33 to Joint Chequing. identity-QdjtaaPm9YBJDGxU0GFV30N9xoS" },
  { id:"WOCOO-21173", summary:"PPMC & VISA CC - Decline Trxns", type:"Credit Card: Transactions", status:"Pending External", priority:"Medium", labels:"jira_escalated", created:"2026-05-05", description:"Premium client declined transactions in Morocco on PPMC and Visa CC. Need flight home. identity-PSKjs1YxFlfnLKmy1rRU0GSkxzc" },
  { id:"WOCOO-21122", summary:"NSF Error When the client had enough funds", type:"Prepaid Card: Transactions", status:"Pending CS", priority:"Medium", labels:"", created:"2026-05-01", description:"Core client had sufficient funds but error withdrawing money. May 1st incident. identity-QRBoMig2OwH0ozNW5KRoENHOOg0" },
  { id:"WOCOO-21035", summary:"CC bill payment - account hold", type:"Credit Card: Transactions", status:"Pending CS", priority:"Medium", labels:"jira_escalated", created:"2026-04-29", description:"Generation client cannot pay CC bill due to hold on accounts. identity-mJJ1YNmImh5X7kJq5Jxsxkepv61" },
  { id:"WOCOO-20971", summary:"Decline credit card transaction", type:"Credit Card: Transactions", status:"Pending CS", priority:"Medium", labels:"jira_escalated", created:"2026-04-27", description:"Premium client CC declined at BEST WESTERN PLUS Apr 21. Tap exceeded limit; chip+PIN no activity. identity-uACjRL5Hlklz3kc2g0ktsXK3kDI" },
  { id:"WOCOO-20861", summary:"Apple Wallet transaction failing", type:"Prepaid Card: Digital Wallet", status:"Pending CS", priority:"Medium", labels:"jira_escalated", created:"2026-04-23", description:"Core client card active and unlocked but unable to carry out transaction using Apple wallet at Translink. identity-Ng4HqYNk9d6jFAprHoiE4NSyLwD" },
  { id:"WOCOO-20730", summary:"Declined Merchant Refund", type:"Prepaid Card: Transactions", status:"Pending CS", priority:"Medium", labels:"jira_escalated", created:"2026-04-20", description:"Core client refund attempt with merchant declined, not visible in profile. identity-SyWtgUm90A78YcV6mGd9xcc5FRg" },
];

var TICKETS_BY_ASSIGNEE = { albert: TICKETS_ALBERT, esther: TICKETS_ESTHER, luke: TICKETS_LUKE, ishan: TICKETS_ISHAN };

// ============ MCP CONFIG ============
var MCPLOCKER_URL = "https://mcplocker.w10external.com/mcp";
var MCPLOCKER_NAME = "mcplocker";
var ANTHROPIC_URL = "https://api.anthropic.com/v1/messages";

// ============ CLASSIFICATION & HELPERS ============
function classifyTicket(t) {
  var s=(t.summary||"").toLowerCase(),ty=(t.type||"").toLowerCase(),d=(t.description||"").toLowerCase();
  if(ty==="credit card: overpayment")return"Credit Card: Overpayment / Negative Balance";
  if(s.includes("visa airport companion")||(s.includes("vip")&&s.includes("companion"))||s.includes("visa companion"))return"Visa Airport Companion";
  if(s.includes("overpayment")||s.includes("overbalance")||s.includes("over balance")||(s.includes("negative")&&s.includes("balance"))||s.includes("transfer to chequing")||s.includes("transfer request")||s.includes("reversal request")||(s.includes("move")&&(s.includes("balance")||s.includes("chequing")))||d.includes("negative balance")||d.includes("transferred to their chequing")||d.includes("overpayment")||d.includes("overbalance")||d.includes("moved to their chequing")||(d.includes("move")&&d.includes("chequing"))||(s.includes("reversal")&&(d.includes("overpayment")||d.includes("chequing"))))return"Credit Card: Overpayment / Negative Balance";
  if(s.includes("fee rever")||s.includes("fee waiv")||s.includes("fee reimburs")||s.includes("dd coded 600"))return"Credit Card: Fee Reversal / Closure";
  if(s.includes("application")&&(s.includes("reset")||s.includes("close")||s.includes("cancel"))||d.includes("application reset")||(d.includes("reset")&&d.includes("application"))||(d.includes("cancel")&&d.includes("application")))return"CC Application Reset/Close";
  if(ty.includes("prepaid card: transactions")&&(s.includes("decline")||s.includes("mismatch")||s.includes("not supported")))return"Prepaid Card: Declined Transactions";
  if(s.includes("cashback")||s.includes("rewards")||ty.includes("rewards"))return"Credit Card: Rewards / Cashback";
  if(ty.includes("credit card: digital wallet"))return"Credit Card: Digital Wallet";
  if(ty.includes("prepaid card: digital wallet"))return"Prepaid Card: Digital Wallet";
  if(ty.includes("credit card: statements"))return"Credit Card: Statements";
  if(ty.includes("credit card: transactions"))return"Credit Card: Transactions (General)";
  if(ty.includes("credit card: other"))return"Credit Card: Fee Reversal / Closure";
  if(ty.includes("cash: bill payment"))return"Cash: Bill Payment";
  if(ty.includes("cash: e-transfer"))return"Cash: E-transfers";
  if(ty.includes("cash: cheques")||ty.includes("cheque"))return"Cash: Cheques";
  if(ty.includes("prepaid card: transactions"))return"Prepaid Card: Declined Transactions";
  if(s.includes("eligibility"))return"Other / Eligibility Confirmation";
  if(ty.includes("cash:"))return"Cash: E-transfers";
  return"Other / Eligibility Confirmation";
}
function getTriageMethod(t){var l=typeof t.labels==="string"?t.labels:"";if(l.includes("jira_escalated"))return"Escalated";if((t.type||"")==="Other"&&(t.summary||"").includes("Eligibility"))return"Self-serve";return"Manual"}
function getStatusGroup(s){if(!s)return"Other";if(s.includes("Triage"))return"Triage";if(s.includes("Back Office"))return"Back Office";if(s.includes("Pending"))return"Pending";if(s.includes("Done"))return"Done";if(s.includes("Cancel"))return"Cancelled";return"Other"}
function extractIdentityId(d){var m=(d||"").match(/identity-[A-Za-z0-9_-]+/);return m?m[0]:null}
function extractAmount(d){if(!d)return null;var p=[/[-−]?\$\s?([\d,]+\.?\d{0,2})/,/\b([\d,]+\.\d{2})\b/];for(var i=0;i<p.length;i++){var m=d.match(p[i]);if(m){var v=parseFloat(m[1].replace(/,/g,""));if(!isNaN(v)&&v>0)return v}}return null}
function fmtAmt(v){return(v===null||v===undefined||isNaN(v))?"—":"$"+v.toFixed(2)}
function enrichTickets(data){return data.map(function(t){return Object.assign({},t,{category:classifyTicket(t),triageMethod:getTriageMethod(t),statusGroup:getStatusGroup(t.status)})})}

var statusColors={Triage:"#dc2626","Back Office":"#d97706",Pending:"#2563eb",Done:"#16a34a",Cancelled:"#6b7280",Other:"#9333ea"};
var priorityColors={Highest:"#dc2626",High:"#ea580c",Medium:"#ca8a04",Low:"#16a34a",Lowest:"#6b7280"};
var ACCOUNT_ID_RE=/^[CHWN][0-9A-Z]{7,}$/i;
var APPROVERS={luke:{name:"Luke Gazmin",accountId:"712020:9afdb43a-362c-4a1e-a2bd-99df2619b105"},amanda:{name:"Amanda Burke",accountId:"62006b10ed02400069a11d5a"}};
// Luke OOO: Amanda covers <$5K approvals through Fri 2026-10-02; reverts automatically at local midnight.
var LUKE_OOO_UNTIL=new Date(2026,9,3);
var ASSIGNEES=[{name:"Albert Cai",value:"albert"},{name:"Luke Gazmin",value:"luke"},{name:"Esther Liao",value:"esther"},{name:"Ishan Jain",value:"ishan"}];
var EOC_CLIENT_STATUS=[{label:"Core",id:"17688"},{label:"Premium",id:"17689"},{label:"Generation",id:"17690"}];

// ============ MOVE MODAL CONSTANTS ============
var ERRORS_SHEET_ID = "1QRfVuodNRXBAArzIoHPXAUpFdjZ0R8C7aOypcnpx_LA";
var ERRORS_SHEET_NAME = "Errors";
var MOVES_SHEET_NAME = "Moves";
